### ISSUE TITLE
What should I do as a macOS user? 

### ISSUE THREAD

**Issue by sudis** [cemahseri/DiscordCrasherVideoGenerator#10]
Hello Dear Cemahseri,
I was studying your amazing project. As a macOS user, I was intrigued by some lines that I believed to be true. Do macOS users have to do the sexual act to use this project? You did not write how this sexual act should be.

1- Can it be done as normal masturbation? 

2- If the person is Heterosexual, can they choose normal intercourse instead of doing this? 

3- If the person is Asexual, is it enough that he/she has just committed the sexual act in his/her mind? 

4- Again, as one of the same questions, if the person is homosexual, it is certain that it will give them an advantage. After all, they are already doing that. Wouldn't that give them an unfair advantage? 

I would be very grateful if you could help me answer my questions above. 

Sincerely,
Magdalena Sude.

**Comment by cemahseri** [comment]
Hello there! Thanks for checking out my little project. I am really sorry for not eloborating the sexual process.

Well, sadly those lines are true. macOS users really have to fuck themselves.

1. It's kind of complicated and partly depends on the user's sex. If he is male, then it can be done via masturbation. If she is male, penetration is mandatory on the masturbation. Elsewise, it will not count.
2. DiscordCrasherVideoGenerator:tm: respects all human beings, regardless of their sexual orientation. But sadly, since normal intercourse is not counted as fucking himself/herself. Still, directly fucking themselves or masturbation is needed.
3. As I said, DiscordCrasherVideoGenerator:tm: respect everybody, but it doesn't do any exception for them. So everybody, including asexual macOS users, have to do sexual process physically. A small price to pay for salvation...
4. Yes, I'm aware of this unfair advantage, but there is nothing I can do. It's the law.

If I couldn't help you out as you expected, feel free to reopen the issue.

Best wishes.
